import Foundation
import SwiftData

/// Mirror of the per-video Drive folder the bridge/extension writes:
/// `<videoId>/cues.json` + `<videoId>/meta.json` under fixed folder
/// `DriveOAuthConfig.folderId`, via Drive REST (not Files / NSFileCoordinator).
///
/// Freshness is the Lamport `rev` in `meta.json`, never a timestamp: Mac and iPad clocks
/// drift, and Drive file mtime is the sync time, not the edit time.
@MainActor
enum DriveScriptsService {
    /// Stable per-install id, mirroring the bridge's `data/config/device_id.txt`.
    static let deviceId: String = {
        let key = "driveDeviceId"
        if let saved = UserDefaults.standard.string(forKey: key), !saved.isEmpty { return saved }
        let fresh = "ipad-" + UUID().uuidString.prefix(8).lowercased()
        UserDefaults.standard.set(fresh, forKey: key)
        return fresh
    }()

    // MARK: - Sync

    /// Pull when Drive is ahead, otherwise push iPad edits back as a patch.
    /// Returns true when SwiftData changed and the caller must reload its cues.
    @discardableResult
    static func sync(videoId: String, context: ModelContext) async -> Bool {
        guard !videoId.isEmpty, DriveAuthService.shared.hasToken else { return false }
        do {
            return try await syncThrowing(videoId: videoId, context: context)
        } catch {
            return false
        }
    }

    /// Whole folder → SwiftData. Returns a status line for the side panel.
    static func syncAll(context: ModelContext) async -> String {
        guard DriveAuthService.shared.hasToken else { return "Chưa Connect Drive" }
        do {
            let folders = try await DriveAPIClient.listVideoFolders()
            var pulled = 0
            for folder in folders {
                if try await syncThrowing(videoId: folder.name, context: context) { pulled += 1 }
            }
            return folders.isEmpty
                ? "Drive: chưa thấy folder video nào"
                : "Drive: \(folders.count) video · nạp mới \(pulled)"
        } catch {
            return "Drive: \(error.localizedDescription)"
        }
    }

    private static func syncThrowing(videoId: String, context: ModelContext) async throws -> Bool {
        let folderId = try await DriveAPIClient.ensureVideoFolder(videoId: videoId)
        let children = try await DriveAPIClient.children(folderId: folderId)
        guard let cuesFileId = children["cues.json"] else { return false }

        let cuesText = try await DriveAPIClient.getText(fileId: cuesFileId)
        guard let cuesData = cuesText.data(using: .utf8),
              let cuesRoot = (try? JSONSerialization.jsonObject(with: cuesData)) as? [String: Any]
        else { return false }

        var meta: [String: Any]
        if let metaId = children["meta.json"],
           let metaText = try? await DriveAPIClient.getText(fileId: metaId),
           let metaData = metaText.data(using: .utf8),
           let parsed = (try? JSONSerialization.jsonObject(with: metaData)) as? [String: Any] {
            meta = parsed
        } else {
            meta = cuesRoot["meta"] as? [String: Any] ?? [:]
        }
        let driveRev = DriveAPIClient.parseRev(meta)

        let script = fetchScript(videoId: videoId, context: context)
        if script == nil || driveRev > (script?.rev ?? 0) {
            return pull(videoId: videoId, cuesData: cuesData, meta: meta, rev: driveRev, context: context)
        }

        guard let script,
              let live = liveCues(videoId: videoId, context: context),
              var patched = patchedCues(original: cuesRoot, cues: live)
        else { return false }

        let rev = max(driveRev, script.rev) + 1
        meta["video_id"] = videoId
        meta["rev"] = rev
        meta["deviceId"] = deviceId
        meta["updated_at"] = bridgeTimestamp(Date())
        meta["cue_count"] = live.count
        meta["owned"] = true
        patched["meta"] = meta
        guard let cuesOut = encode(patched), let metaOut = encode(meta),
              let cuesStr = String(data: cuesOut, encoding: .utf8),
              let metaStr = String(data: metaOut, encoding: .utf8)
        else { return false }

        _ = try await DriveAPIClient.putText(
            folderId: folderId, name: "cues.json", text: cuesStr, fileId: cuesFileId
        )
        _ = try await DriveAPIClient.putText(
            folderId: folderId, name: "meta.json", text: metaStr, fileId: children["meta.json"]
        )
        // script.txt is regenerated by the bridge on mirror — no iPad renderer for its header.
        script.rev = rev
        script.deviceId = deviceId
        try? context.save()
        return false
    }

    private static func pull(
        videoId: String,
        cuesData: Data,
        meta: [String: Any],
        rev: Int,
        context: ModelContext
    ) -> Bool {
        guard let text = String(data: cuesData, encoding: .utf8) else { return false }
        let rows = ScriptCue.parseImportRows(text)
        guard !rows.isEmpty else { return false }
        _ = ScriptCue.importRows(videoId: videoId, rows: rows, mode: .replace, includeJA: true, context: context)
        if let script = fetchScript(videoId: videoId, context: context) {
            script.rev = rev
            script.deviceId = meta["deviceId"] as? String ?? ""
            if let title = meta["title"] as? String, !title.isEmpty { script.title = title }
            try? context.save()
        }
        return true
    }

    // MARK: - Patch merge

    /// Patch, never rewrite: iPad owns only `start_media_time` / `end_media_time` / `source` /
    /// `en` / `vi`. `tokens`, `mt_locked`, `translation_source` — which iPad has no field for —
    /// ride along untouched. Returns nil when nothing changed, which is what stops the rev
    /// ping-pong between iPad and PC.
    static func patchedCues(original: [String: Any], cues: [ScriptCue]) -> [String: Any]? {
        let old = (original["cues"] as? [[String: Any]]) ?? []
        var byId: [String: [String: Any]] = [:]
        for cue in old {
            if let id = cue["id"] as? String, !id.isEmpty { byId[id] = cue }
        }

        var out: [[String: Any]] = []
        var changed = false
        for cue in cues {
            let startSec = cue.startTime / 1000
            let endSec = (cue.startTime + max(cue.duration, 0)) / 1000
            let en = cue.textEN ?? ""
            let vi = cue.textVI ?? ""
            guard var row = byId[cue.id] else {
                out.append([
                    "id": cue.id,
                    "start_media_time": startSec,
                    "end_media_time": endSec,
                    "source": cue.textJA,
                    "en": en,
                    "vi": vi,
                    "tokens": [],
                    "translated": !(en.isEmpty && vi.isEmpty),
                    "text_source": "manual",
                    "mt_locked": false,
                    "translation_source": "",
                ])
                changed = true
                continue
            }
            // ±0.5ms tolerance: sec → ms → sec float drift must not read as an edit.
            if abs(double(row["start_media_time"]) - startSec) > 0.0005 {
                row["start_media_time"] = startSec
                changed = true
            }
            if abs(double(row["end_media_time"]) - endSec) > 0.0005 {
                row["end_media_time"] = endSec
                changed = true
            }
            if (row["source"] as? String ?? "") != cue.textJA {
                row["source"] = cue.textJA
                changed = true
            }
            if (row["en"] as? String ?? "") != en || (row["vi"] as? String ?? "") != vi {
                row["en"] = en
                row["vi"] = vi
                row["translated"] = !(en.isEmpty && vi.isEmpty)
                changed = true
            }
            out.append(row)
        }
        // Covers tombstones, inserts and reorder in one comparison.
        if old.map({ $0["id"] as? String ?? "" }) != out.map({ $0["id"] as? String ?? "" }) { changed = true }
        guard changed else { return nil }

        var root = original
        root["cues"] = out
        return root
    }

    // MARK: - Helpers

    private static func encode(_ object: [String: Any]) -> Data? {
        try? JSONSerialization.data(
            withJSONObject: object,
            options: [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes]
        )
    }

    private static func fetchScript(videoId: String, context: ModelContext) -> VideoScript? {
        let descriptor = FetchDescriptor<VideoScript>(predicate: #Predicate { $0.videoId == videoId })
        return try? context.fetch(descriptor).first
    }

    private static func liveCues(videoId: String, context: ModelContext) -> [ScriptCue]? {
        let live = ScriptCue.load(videoId: videoId, context: context)
            .filter { !$0.isDeleted }
            .sorted { $0.startTime < $1.startTime }
        // Never push an empty list over a Drive script — that would be a silent wipe.
        return live.isEmpty ? nil : live
    }

    fileprivate static func double(_ value: Any?) -> Double { (value as? NSNumber)?.doubleValue ?? 0 }

    /// Bridge writes local time without a zone (`%Y-%m-%dT%H:%M:%S`).
    private static func bridgeTimestamp(_ date: Date) -> String {
        let f = DateFormatter()
        f.locale = Locale(identifier: "en_US_POSIX")
        f.dateFormat = "yyyy-MM-dd'T'HH:mm:ss"
        return f.string(from: date)
    }
}

/// The one check for patch-merge: PC-only fields must survive an iPad write, and an
/// unedited script must produce no write at all (else iPad and PC bump `rev` forever).
enum DriveScriptsSmoke {
    @MainActor
    static func run() {
        let json = """
        {"video_id":"v","cues":[
          {"id":"a","start_media_time":0.599,"end_media_time":2.0,"source":"あ","en":"A","vi":"",
           "tokens":[{"surface":"あ"}],"translated":true,"text_source":"yt","mt_locked":true,"translation_source":"import"},
          {"id":"b","start_media_time":3.0,"end_media_time":4.0,"source":"い","en":"","vi":"",
           "tokens":[],"translated":false,"text_source":"yt","mt_locked":false,"translation_source":""}
        ],"meta":{"rev":5}}
        """
        let root = (try! JSONSerialization.jsonObject(with: Data(json.utf8))) as! [String: Any]

        func cue(_ id: String, _ startMs: Double, _ endMs: Double, _ ja: String, _ en: String?, _ vi: String?) -> ScriptCue {
            ScriptCue(id: id, startTime: startMs, duration: endMs - startMs, textJA: ja, textEN: en, textVI: vi)
        }

        // Same content back → nil, so no rev bump and no ping-pong (0.599s → 599ms → 0.599s).
        let unchanged = DriveScriptsService.patchedCues(
            original: root,
            cues: [cue("a", 599, 2000, "あ", "A", ""), cue("b", 3000, 4000, "い", "", "")]
        )
        assert(unchanged == nil, "unedited script must not write")

        // Edit VI on `a`, tombstone `b`, add a new cue.
        let patched = DriveScriptsService.patchedCues(
            original: root,
            cues: [cue("a", 599, 2000, "あ", "A", "Xin chào"), cue("new", 5000, 6000, "う", nil, nil)]
        )
        let cues = patched?["cues"] as? [[String: Any]]
        assert(cues?.count == 2, "tombstoned cue removed, new cue appended")
        assert(cues?[0]["vi"] as? String == "Xin chào", "vi written")
        assert((cues?[0]["tokens"] as? [Any])?.count == 1, "tokens preserved")
        assert(cues?[0]["mt_locked"] as? Bool == true, "mt_locked preserved")
        assert(cues?[0]["translation_source"] as? String == "import", "translation_source preserved")
        assert(cues?[0]["text_source"] as? String == "yt", "text_source preserved")
        assert(cues?[1]["id"] as? String == "new", "new cue kept in start order")
        assert((cues?[1]["tokens"] as? [Any])?.isEmpty == true, "new cue gets empty tokens")
        assert(abs(DriveScriptsService.double(cues?[1]["start_media_time"]) - 5.0) < 1e-9, "ms → sec on write")
        assert((patched?["meta"] as? [String: Any])?["rev"] as? Int == 5, "untouched keys ride along")

        print("[DriveScriptsSmoke] ok")
    }
}
