import type { SavedWord } from "@/types/vocab";

export const IS_DEV = process.env.NODE_ENV === "development";

/** Demo seeds — replace later via extension messaging / bridge. */
export const MOCK_SAVED_WORDS: SavedWord[] = [
  {
    lemma: "遭難",
    reading: "そうなん",
    glossVi: "gặp nạn; bị nạn (trên biển…)",
    glossEn: "disaster; shipwreck",
    status: "learning",
    jlpt: "n1",
    contextJa: "いかだの上で遭難した船乗り",
    videoTitle: "Demo — caption clip",
    updatedAt: Date.now() - 86400000,
  },
  {
    lemma: "孤独",
    reading: "こどく",
    glossVi: "cô đơn",
    glossEn: "loneliness; solitude",
    status: "learning",
    jlpt: "n1",
    contextJa: "もっと孤独だった",
    videoTitle: "Demo — caption clip",
    updatedAt: Date.now() - 82000000,
  },
  {
    lemma: "初めて",
    reading: "はじめて",
    glossVi: "lần đầu",
    glossEn: "for the first time",
    status: "known",
    jlpt: "n5",
    contextJa: "初めて夜、砂の上で眠りについた",
    updatedAt: Date.now() - 172800000,
  },
  {
    lemma: "住まい",
    reading: "すまい",
    glossVi: "chỗ ở; nhà",
    glossEn: "dwelling; residence",
    status: "known",
    jlpt: "n2",
    contextJa: "人間の住まいから何千マイルも離れて",
    updatedAt: Date.now() - 200000000,
  },
  {
    lemma: "いかだ",
    reading: "いかだ",
    glossVi: "bè",
    glossEn: "raft",
    status: "special",
    jlpt: "n1",
    contextJa: "海の真ん中のいかだの上で",
    updatedAt: Date.now() - 50000000,
  },
  {
    lemma: "珍語",
    reading: "ちんご",
    glossVi: "(từ hiếm — demo)",
    glossEn: "rare word (demo)",
    status: "ignored",
    jlpt: "",
    contextJa: "（珍語）",
    updatedAt: Date.now() - 300000000,
  },
  {
    lemma: "眠り",
    reading: "ねむり",
    glossVi: "giấc ngủ",
    glossEn: "sleep",
    status: "learning",
    jlpt: "n3",
    contextJa: "砂の上で眠りについた",
    updatedAt: Date.now() - 40000000,
  },
  {
    lemma: "真ん中",
    reading: "まんなか",
    glossVi: "giữa; trung tâm",
    glossEn: "middle; center",
    status: "known",
    jlpt: "n3",
    contextJa: "海の真ん中のいかだ",
    updatedAt: Date.now() - 90000000,
  },
];
